# Alacritty
# Config file opts: https://alacritty.org/config-alacritty.html

[window]
dimensions = { columns = 128, lines = 38 }
position = { x = 300, y = 420 }
padding = { x = 0, y = 0 }
decorations = "None"
opacity = 0.74
blur = false

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 17.25

# Colors (Horizon Dark)
[colors.primary]
background = '#1c1e26'
foreground = '#e0e0e0'

[colors.normal]
black = '#16161c'
red = '#e95678'
green = '#29d398'
yellow = '#fab795'
blue = '#26bbd9'
magenta = '#ee64ac'
cyan = '#59e1e3'
white = '#d5d8da'

[colors.bright]
black = '#5b5858'
red = '#ec6a88'
green = '#3fdaa4'
yellow = '#fbc3a7'
blue = '#3fc4de'
magenta = '#f075b5'
cyan = '#6be4e6'
white = '#d5d8da'

[cursor]
style = { shape = "Underline" }

[keyboard]
bindings = [
  { key = "Escape", mods = "Command", action = "ToggleSimpleFullscreen" },
]
